# Generated by Django 3.0.2 on 2020-01-16 20:53

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200116_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='media/pfps/default.png', upload_to='media/pfps', validators=[main.validators.pfp]),
        ),
    ]
