# Generated by Django 3.0.2 on 2020-01-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
    ]
