#admin.py is used to configure the settings for the admin view of the website (available at admin/)
from django.contrib import admin
from .models import Post

#The below class is used to configure the admin view for all posts
class postAdmin(admin.ModelAdmin):
    list_display = ('title', 'slug', 'userID', 'status', 'published', 'tag1', 'tag2') #Fields shown at a glance, easier for identification
    list_filter = ("status",) #Defines that you can filter objects by whether they've been published or not
    search_fields = ['title', 'content', 'tag1', 'tag2'] #Fields that you can search by, makes finding specific posts easier
    prepopulated_fields = {'slug': ('title',)} #Autofills the slug to an autogenerated variable based on the title

#Registers classes into the admin site and allows for them to be edited
admin.site.register(Post, postAdmin) 

