# Generated by Django 3.0.1 on 2020-01-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.TextField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.TextField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.TextField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='tag4',
            field=models.TextField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='tag5',
            field=models.TextField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
