# Generated by Django 3.0.1 on 2020-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200105_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag1',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag2',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag3',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag4',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag5',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
