# Generated by Django 3.0.1 on 2020-01-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200105_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag1',
            field=models.IntegerField(choices=[(0, 'Alt-Rock'), (1, 'Blues'), (2, 'Classical'), (3, 'Country'), (4, 'Dance'), (5, 'Drum and Bass'), (6, 'Dubstep'), (7, 'Easy listening'), (8, 'Electro'), (9, 'Emo'), (10, 'Eurobeat'), (11, 'Experimental'), (12, 'Fast'), (13, 'Folk'), (14, 'Funk'), (15, 'Garage'), (16, 'Grime'), (17, 'Grunge'), (18, 'Hip Hop'), (19, 'Indie'), (20, 'Jazz'), (21, 'Latin'), (22, 'Lo-Fi'), (23, 'Metal'), (24, 'Motown'), (25, 'Mod'), (26, 'Opera'), (27, 'Pop'), (28, 'Prog Rock'), (29, 'Punk'), (30, 'R&B'), (31, 'Rap'), (32, 'Reggae'), (33, 'Rock'), (34, 'Slow'), (35, 'Soul'), (36, 'Techno'), (37, 'Trance'), (38, 'Trip-Hop')], default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag2',
            field=models.IntegerField(choices=[(0, 'Alt-Rock'), (1, 'Blues'), (2, 'Classical'), (3, 'Country'), (4, 'Dance'), (5, 'Drum and Bass'), (6, 'Dubstep'), (7, 'Easy listening'), (8, 'Electro'), (9, 'Emo'), (10, 'Eurobeat'), (11, 'Experimental'), (12, 'Fast'), (13, 'Folk'), (14, 'Funk'), (15, 'Garage'), (16, 'Grime'), (17, 'Grunge'), (18, 'Hip Hop'), (19, 'Indie'), (20, 'Jazz'), (21, 'Latin'), (22, 'Lo-Fi'), (23, 'Metal'), (24, 'Motown'), (25, 'Mod'), (26, 'Opera'), (27, 'Pop'), (28, 'Prog Rock'), (29, 'Punk'), (30, 'R&B'), (31, 'Rap'), (32, 'Reggae'), (33, 'Rock'), (34, 'Slow'), (35, 'Soul'), (36, 'Techno'), (37, 'Trance'), (38, 'Trip-Hop')], default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag3',
            field=models.IntegerField(choices=[(0, 'Alt-Rock'), (1, 'Blues'), (2, 'Classical'), (3, 'Country'), (4, 'Dance'), (5, 'Drum and Bass'), (6, 'Dubstep'), (7, 'Easy listening'), (8, 'Electro'), (9, 'Emo'), (10, 'Eurobeat'), (11, 'Experimental'), (12, 'Fast'), (13, 'Folk'), (14, 'Funk'), (15, 'Garage'), (16, 'Grime'), (17, 'Grunge'), (18, 'Hip Hop'), (19, 'Indie'), (20, 'Jazz'), (21, 'Latin'), (22, 'Lo-Fi'), (23, 'Metal'), (24, 'Motown'), (25, 'Mod'), (26, 'Opera'), (27, 'Pop'), (28, 'Prog Rock'), (29, 'Punk'), (30, 'R&B'), (31, 'Rap'), (32, 'Reggae'), (33, 'Rock'), (34, 'Slow'), (35, 'Soul'), (36, 'Techno'), (37, 'Trance'), (38, 'Trip-Hop')], default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag4',
            field=models.IntegerField(choices=[(0, 'Alt-Rock'), (1, 'Blues'), (2, 'Classical'), (3, 'Country'), (4, 'Dance'), (5, 'Drum and Bass'), (6, 'Dubstep'), (7, 'Easy listening'), (8, 'Electro'), (9, 'Emo'), (10, 'Eurobeat'), (11, 'Experimental'), (12, 'Fast'), (13, 'Folk'), (14, 'Funk'), (15, 'Garage'), (16, 'Grime'), (17, 'Grunge'), (18, 'Hip Hop'), (19, 'Indie'), (20, 'Jazz'), (21, 'Latin'), (22, 'Lo-Fi'), (23, 'Metal'), (24, 'Motown'), (25, 'Mod'), (26, 'Opera'), (27, 'Pop'), (28, 'Prog Rock'), (29, 'Punk'), (30, 'R&B'), (31, 'Rap'), (32, 'Reggae'), (33, 'Rock'), (34, 'Slow'), (35, 'Soul'), (36, 'Techno'), (37, 'Trance'), (38, 'Trip-Hop')], default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag5',
            field=models.IntegerField(choices=[(0, 'Alt-Rock'), (1, 'Blues'), (2, 'Classical'), (3, 'Country'), (4, 'Dance'), (5, 'Drum and Bass'), (6, 'Dubstep'), (7, 'Easy listening'), (8, 'Electro'), (9, 'Emo'), (10, 'Eurobeat'), (11, 'Experimental'), (12, 'Fast'), (13, 'Folk'), (14, 'Funk'), (15, 'Garage'), (16, 'Grime'), (17, 'Grunge'), (18, 'Hip Hop'), (19, 'Indie'), (20, 'Jazz'), (21, 'Latin'), (22, 'Lo-Fi'), (23, 'Metal'), (24, 'Motown'), (25, 'Mod'), (26, 'Opera'), (27, 'Pop'), (28, 'Prog Rock'), (29, 'Punk'), (30, 'R&B'), (31, 'Rap'), (32, 'Reggae'), (33, 'Rock'), (34, 'Slow'), (35, 'Soul'), (36, 'Techno'), (37, 'Trance'), (38, 'Trip-Hop')], default='none'),
        ),
    ]
