# Generated by Django 3.0.1 on 2020-01-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200106_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag5',
        ),
        migrations.AlterField(
            model_name='post',
            name='tag1',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Alt-Rock'), (2, 'Blues'), (3, 'Classical'), (4, 'Country'), (5, 'Dance'), (6, 'Drum and Bass'), (7, 'Dubstep'), (8, 'Easy listening'), (9, 'Electro'), (10, 'Emo'), (11, 'Eurobeat'), (12, 'Experimental'), (13, 'Fast'), (14, 'Folk'), (15, 'Funk'), (16, 'Garage'), (17, 'Grime'), (18, 'Grunge'), (19, 'Hip Hop'), (20, 'Indie'), (21, 'Jazz'), (22, 'Latin'), (23, 'Lo-Fi'), (24, 'Metal'), (25, 'Motown'), (26, 'Mod'), (27, 'Opera'), (28, 'Pop'), (29, 'Prog Rock'), (30, 'Punk'), (31, 'R&B'), (32, 'Rap'), (33, 'Reggae'), (34, 'Rock'), (35, 'Slow'), (36, 'Soul'), (37, 'Techno'), (38, 'Trance'), (39, 'Trip-Hop')], default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag2',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Alt-Rock'), (2, 'Blues'), (3, 'Classical'), (4, 'Country'), (5, 'Dance'), (6, 'Drum and Bass'), (7, 'Dubstep'), (8, 'Easy listening'), (9, 'Electro'), (10, 'Emo'), (11, 'Eurobeat'), (12, 'Experimental'), (13, 'Fast'), (14, 'Folk'), (15, 'Funk'), (16, 'Garage'), (17, 'Grime'), (18, 'Grunge'), (19, 'Hip Hop'), (20, 'Indie'), (21, 'Jazz'), (22, 'Latin'), (23, 'Lo-Fi'), (24, 'Metal'), (25, 'Motown'), (26, 'Mod'), (27, 'Opera'), (28, 'Pop'), (29, 'Prog Rock'), (30, 'Punk'), (31, 'R&B'), (32, 'Rap'), (33, 'Reggae'), (34, 'Rock'), (35, 'Slow'), (36, 'Soul'), (37, 'Techno'), (38, 'Trance'), (39, 'Trip-Hop')], default='none'),
        ),
    ]
