# Generated by Django 3.0.2 on 2020-01-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
