# Generated by Django 3.0.2 on 2020-01-16 12:23

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(null=True, upload_to='media/audio', validators=[main.validators.audioFile]),
        ),
    ]
