# Generated by Django 3.0.2 on 2020-01-16 21:45

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200116_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/audio', validators=[main.validators.audioFile]),
        ),
    ]
