# Generated by Django 3.0.2 on 2020-02-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
